### ISSUE TITLE
ImportError: cannot import name Ensure_dir when trying to run the code in lpy

### ISSUE THREAD

**Issue by werner291** [openalea-incubator/MAppleT#10]
Hello,

so as a follow-up from #9, I've now got LPy and MappleT installed, but I get the following error when I click "Run" or "Animate":

```
Traceback (most recent call last):
  File "/home/werner/miniconda3/envs/MappleT/lib/python2.7/site-packages/OpenAlea.Lpy-2.7.1-py2.7-linux-x86_64.egg/openalea/lpy/gui/lpystudio.py", line 684, in run
    simu.updateLsystemCode()
  File "/home/werner/miniconda3/envs/MappleT/lib/python2.7/site-packages/OpenAlea.Lpy-2.7.1-py2.7-linux-x86_64.egg/openalea/lpy/gui/simulation.py", line 538, in updateLsystemCode
    res = self.lsystem.set(lpycode,{},self.lpywidget.showPyCode)
  File "/home/werner/miniconda3/envs/MappleT/lib/python2.7/site-packages/OpenAlea.PlantGL-2.23.2-py2.7-linux-x86_64.egg/openalea/plantgl/scenegraph/__init__.py", line 20, in newFunc
    return func(*args, **kwargs)
  File "/home/werner/miniconda3/envs/MappleT/lib/python2.7/site-packages/OpenAlea.Lpy-2.7.1-py2.7-linux-x86_64.egg/openalea/lpy/__init__.py", line 140, in lsystem_set
    return self.setCode(code,parameters,debug)
  File "<string>", line 37, in <module>
ImportError: cannot import name Ensure_dir
```

**Comment by werner291** [comment]
Oh hold on, I'm getting a new PlantGL window... But nothing seems to be happening in it.

**Comment by werner291** [comment]
Appears related to this line: https://github.com/openalea-incubator/MAppleT/blob/master/share/data/stocatree.lpy#L37

**Comment by werner291** [comment]
Indeed, I don't see the function being referred to in here: https://github.com/openalea-incubator/MAppleT/blob/master/src/stocatree/rw_tools.py
